### ISSUE TITLE
I want to contribute this project

### ISSUE THREAD

**Issue by kty4119** [Alex1304/jdash#11]
Hello Alex1304. I'm first time in git-hub. but interested in 'geometry dash'. And  i can help you. for example add more contents to "read me", translate for other country. Also  i can use java. Please tell me if you can. thank you!

**Comment by Alex1304** [comment]
Hi,
Welcome I guess. Of course I am open to contributions, there is no guidelines set in stone yet, but I would be glad to receive help from others.
Though, I'm not sure about what you're suggesting to improve. If you think the readme needs more content, can you elaborate more on it? About the translation, I'm not sure what you mean. Neither the docs nor the code need to be translated, coding is usually done exclusively in English.

**Comment by kty4119** [comment]
I'd like to help you add a guideline for Stone But I don't know exactly what Stone is talking about. If you don't mind, let me know what Stone is, and I'll also think about what to add to the REAEME. I am sorry to reply late.
